pom.xml, src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProvider.java, src/main/java/com/google/cloud/spanner/r2dbc/util/Assert.java, src/main/resources/META-INF/services/io.r2dbc.spi.ConnectionFactoryProvider, src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProviderTest.java, src/test/java/com/google/cloud/spanner/r2dbc/util/AssertTest.java
Nothing else would work unless factory discovery file is in META-INF, and `SpannerConnectionFactoryProvider` returns true, so this was the first step. The remaining boilerplate from the WIP will follow.
Also:
* added dependency on Project Reactor.
* added Assert class for very basic argument checking. Would be nice to not duplicate this in every driver, but Spring is too heavy of a required dependency. Guava may be appropriate if we need anything more complex.
=> Enable our SpannerConnectionFactory for driver name 'spanner'

.mvn/maven.config, pom.xml, src/main/java/com/google/cloud/spanner/r2dbc/client/Client.java, src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java
Also introduces the Client abstraction to hide interactions with the
gRPC Spanner service, and implements the basic executeStreamingSql
method wrapping the result into a Reactive Streams
Publisher<PartialResultSet>.
=> Switch to gRPC client for Cloud Spanner

src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java
As per [Mark's comment](https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/pull/23#discussion_r281350638), modifies the executeStreamingSql method to use `Flux.create` instead of creating Publisher manually.
=> Change ExecuteStreamingSql style to use Flux.create

pom.xml, src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java, src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfiguration.java, src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactory.java, src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProvider.java, src/main/java/com/google/cloud/spanner/r2dbc/client/Client.java, src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java, src/main/java/com/google/cloud/spanner/r2dbc/util/ObservableReactiveUtil.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfigurationTest.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProviderTest.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryTest.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerIntegrationTest.java, src/test/java/com/google/cloud/spanner/r2dbc/util/ObservableReactiveUtilTest.java
This change:
* Creates a real `Connection` object with minimum necessary settings.
* When a new Connection is created, it creates a new Spanner session and keeps its name. The session name is necessary for most future operations.
* Added a utility `ObservableReactiveUtil` that takes care of the boilerplate of converting from `StreamObservable` into a `Mono`.
* There is a new integration test, gated with `it.spanner`. You'll have to create a new instance "reactivetest" and a new database "testdb" to run it with no errors. The proper integration setup will be done in #14 .
* I added a _test-only_ dependency on `com.google.cloud:google-cloud-core` to take advantage of `ServiceOptions` project ID autodiscovery. Edit: decided to keep it as is for now; possibly remove completely in the future.
=> create R2DBC connection as a Spanner session created over gRPC

src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java, src/main/java/com/google/cloud/spanner/r2dbc/client/Client.java, src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java
This adds `rollback()` to the SpannerConnection implementation.
Contributes to #35.
=> Add Rollbacks to Spanner Connection

src/main/java/com/google/cloud/spanner/r2dbc/SpannerRow.java, src/main/java/com/google/cloud/spanner/r2dbc/codecs/DefaultCodecs.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerRowTest.java
This implements the get() method for Spanner rows.
Contributes to #34.
=> Implement basic get() functionality for Spanner rows

src/main/java/com/google/cloud/spanner/r2dbc/SpannerColumnMetadata.java, src/main/java/com/google/cloud/spanner/r2dbc/SpannerResult.java, src/main/java/com/google/cloud/spanner/r2dbc/SpannerRow.java, src/main/java/com/google/cloud/spanner/r2dbc/SpannerRowMetadata.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerColumnMetadataTest.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerResultTest.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerRowMetadataTest.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerRowTest.java
This implements the `SpannerRowMetadata` and `SpannerColumnMetadata` objects. Integrates them with `SpannerRow`.
Fixes #34.
Fixes #50.
=> Implement Spanner Row and Column Metadata

pom.xml, src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java, src/test/java/com/google/cloud/spanner/r2dbc/client/GrpcClientTest.java
This test involes starting an embedded gRPC server because there is no
way to mock `SpannerStub`, which a final class.
Fixes #24.
=> Add a test for GrpcClient.executeStreamingSql

pom.xml, src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProvider.java, src/main/java/com/google/cloud/spanner/r2dbc/SpannerRowMetadata.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProviderTest.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerRowMetadataTest.java
The upgrade added a couple of trivial interface methods.
While I was there, I folded everything under a single for-loop in `SpannerRowMetadata`. It already had a for-loop and two stream pipeline. Since now there are three different pieces of data we need to keep track of, a single for-loop is simpler.
Fixes #58 .
=> Upgrade to SPI 0.8, add missing interface methods

src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java, src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java, src/main/java/com/google/cloud/spanner/r2dbc/client/Client.java, src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerStatementTest.java, src/test/java/com/google/cloud/spanner/r2dbc/client/GrpcClientTest.java
As per discussion today with R2DBC folks, this PR modifies `SpannerConnection` to set the transaction as a volatile property of the connection class.
=> Set Transaction as Volatile Variable in Connection

src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java, src/main/java/com/google/cloud/spanner/r2dbc/util/ObservableReactiveUtil.java, src/test/java/com/google/cloud/spanner/r2dbc/util/ObservableReactiveUtilTest.java
This modifies the retry logic of the driver to propagate `R2dbcTransientExceptions` if a call fails instead of attempting to retry on the driver-side.
=> Modify Retry Approach to Propagate Errors

pom.xml
Provides a SLF4J binder for tests. Fixes #67.
**Note:** the dep must be test-scoped because "embedded components" like libraries or drivers should not specify a logging provider and leave the decision to the client: http://www.slf4j.org/codes.html#StaticLoggerBinder
=> Add a SLF4J logging provider for tests.

src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java, src/main/java/com/google/cloud/spanner/r2dbc/statement/StatementParser.java, src/main/java/com/google/cloud/spanner/r2dbc/statement/StatementType.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProviderTest.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerStatementTest.java, src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerIT.java, src/test/java/com/google/cloud/spanner/r2dbc/statement/StatementParserTest.java
This adds the initial helper classes to parse statement types.
Contributes to DML and DDL efforts in which statement type must be known.
=> Add Helper Classes to Parse Statement Types

src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java, src/main/java/com/google/cloud/spanner/r2dbc/statement/StatementBindings.java, src/main/java/com/google/cloud/spanner/r2dbc/statement/TypedNull.java, src/test/java/com/google/cloud/spanner/r2dbc/statement/StatementBindingsTest.java
Moves the Statement bindings logic to separate class for organization.
Purpose for doing this: This will allow us to add more logic to the statement class to support DML, DDL, and normal queries without the class becoming too big.
=> Move Statement Bindings to Separate Class for Organization

src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java, src/main/java/com/google/cloud/spanner/r2dbc/client/Client.java, src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerStatementTest.java, src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerIT.java
=> Batch DML support

src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerIT.java
Switching to `ExecuteBatchDml` lowered the amount of data that could be sent without tripping `INVALID_ARGUMENT: Request payload size exceeds the limit: 1048576 bytes.`.
=> decimate request size

README.md, src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfiguration.java, src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProvider.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfigurationTest.java
Allow DDL timeout and poll settings to be propagated from the spanner configuration settings.
=> Add DDL options Propagation

.kokoro/build.sh, .kokoro/common.sh, .kokoro/continuous.cfg, .kokoro/release_snapshot.sh, pom.xml
Adds `continous.cfg` build configuration for Kokoro. The job first builds the project skipping integration tests, and then deploys (publishes) the snapshot version to Sonatype Snapshots Repository. See: https://oss.sonatype.org/content/repositories/snapshots/com/google/cloud/cloud-spanner-r2dbc/.
This PR also adds all of the [required](https://central.sonatype.org/pages/requirements.html) metadata for publishing to Maven Central.
=> Add Kokoro CI job for publishing snapshots to Maven Central

README.md, src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfiguration.java, src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProvider.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfigurationTest.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProviderTest.java, src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerDdlIT.java
Simple propagation for a Cloud Spanner R2DBC URL to be passed through config.
Fixes #30.
=> Allow URLs to be passed through config

src/main/java/com/google/cloud/spanner/r2dbc/SpannerBatch.java, src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java, src/main/java/com/google/cloud/spanner/r2dbc/client/Client.java, src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerStatementTest.java, src/test/java/com/google/cloud/spanner/r2dbc/client/GrpcClientTest.java, src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerIT.java
Make DML queries propagate error from the response object if present.
[ExecuteBatchDmlResponse contains a Status](https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1#executebatchdmlresponse) which contains message if DML query fails. 
Fixes #148
=> Correctly propagate errors from Batch DML

src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java, src/main/java/com/google/cloud/spanner/r2dbc/util/ObservableReactiveUtil.java, src/main/java/com/google/cloud/spanner/r2dbc/util/SpannerExceptionUtil.java, src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerIT.java, src/test/java/com/google/cloud/spanner/r2dbc/util/SpannerExceptionUtilTest.java
If a Spanner-specific exception is thrown, this adds support to extract the error code if present and construct the appropriate R2dbc exception subclass based upon the error code.
Fixes #154.
=> Propagate Specific R2dbc Exceptions by Error Code

.travis.yml, pom.xml, src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java, src/main/java/com/google/cloud/spanner/r2dbc/SpannerRow.java, src/main/java/com/google/cloud/spanner/r2dbc/SpannerRowMetadata.java, src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerRowTest.java, src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerExample.java, src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerIT.java
* Upgraded SPI to 0.8.0.RC2.
* Upgraded Reactor to Dysprosium-RELEASE.
* Updated `getTransactionIsolationLevel()` to always return SERIALIZABLE, since it's the closest to what Spanner's strong read actually does. 
* Updated `setTransactionIsolationLevel()` to throw `UnsupportedOperationException`. 
* If/when R2DBC supports custom isolation levels, we can introduce the stale read modes.
* Placeholder for `validate()` method (TCK's `validate()` correctly fails).
* Placeholder for `setAutoCommit()` (TCK's `changeAutoCommitCommitsTransaction()` and `sameAutoCommitLeavesTransactionUnchanged()` correctly fail).
* Split up `SpannerRow.get(Object)` into `get(int)` and `get(String)`, per SPI.
* Split `SpannerRowMetadata.getColumnMetadata(Object)` into `getColumnMetadata(int)` and …
=> Update driver to comply with new SPI interfaces

src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java, src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerExample.java
I had thought for some reason that throwing `UnsupportedOperationException` would disable the test automatically, but it needed an override.
Fixes #167 .
=> Savepoints: throw unsupported and disable remaining test

src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionMetadata.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionMetadataTest.java
The metadata is trivial:
* database product name is the same as  in `SpannerConnectionFactoryMetadata`. 
* database version is "n/a" as that is not a relevant concept for Cloud Spanner.
=> Spanner connection-level metadata

src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java
Keeps separate state for autocommit; does not rely on transaction.
A couple of edge case scenarios:
* autocommit was turned off but transaction not started yet. In this case, attempting DML statements will still behave as if autocommit is turned on (a side effect of current GrpcClient.executeBatchDml implementation). I can see an argument for changing this to conform to SPI behavior of committing in-progress transaction upon autocommit being turned off.
* autocommit was turned back on while a non-readwrite transaction is in progress -- this will NOT result in read/write transaction being committed. This is different from the more typical scenario, in which autocommit is turned back on while a Read/Write transaction is in progress, and transaction gets committed automatically. The reason …
=> Add ability to turn autocommit on and off

src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java, src/main/java/com/google/cloud/spanner/r2dbc/client/Client.java, src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java, src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java, src/test/java/com/google/cloud/spanner/r2dbc/client/GrpcClientTest.java, src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerExample.java
* Null out session when connection is closed.
* Local validation relies on having a valid session (it checks for session name, but that's only going to be non-null if and only if the connection is non-null.)
* Remote validation is implemented as a low-level `GrpcClient` healthcheck. It sends a trivial query to Spanner over `executeSql` (as opposed to `executeStreamingSql`).
* Removed session pools from TCK tests
* Suppressed error logging when already-existing tables try to get created. This operation also takes forever; need to check whether pre-querying tables will be faster.
Fixes #162 .
=> Implement connection validation

src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerTestKit.java
Two reasons for failures:
1) Cloud Spanner requires that columns be enumerated in insert statement.
2) Cloud Spanner's "Integer" type is 64 bit, so it maps to a Java Long.
Also: renamed from Example to TestKit to conform to new naming convension.
In the long run, it would be nice to fix without overriding each test, hence r2dbc/r2dbc-spi#138.
=> Fix TCK test failures

src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerIT.java
I was going to just replace `Mono.fromRunnable()` with `Mono.just(/*step verifier here*/)` but ended up inverting the logic, so that `StepVerifier` is always the outer layer. The test purpose feels easier to understand to me this way, but tell me if you'd rather keep the original way.
Fixes #161.
=> remove runnable layer

pom.xml
Also removed commons-io and r2dbc-pool which are no longer used for testing.
=> Use Google Cloud BOM instead of individual versions

cloud-spanner-r2dbc-sample/src/test/java/com/example/BookExampleAppIT.java
This test needs to run as an integration test; otherwise credentials are not available.
=> Rename test to get picked up by Failsafe

pom.xml
Nexus staging plugin checks the value of `skipNexusStagingDeployMojo` property in the last module in reactor ([docs](https://help.sonatype.com/repomanager2/staging-releases/configuring-your-project-for-deployment)). 
More information on this behavior: https://issues.sonatype.org/browse/NEXUS-9138
This PR excludes the samples module from the deploy profile.
=> Exclude sample module from release profile

pom.xml
We don't want to set `autoReleaseAfterClose` to `true`.
We want to use the `drop` job or the `promote` job to decide what to do after staging the artifacts for release to Maven Central.
=> Remove autoReleaseAfterClose property

.travis.yml
In Travis, all steps in the `script` run regardless if the previous one failed. This makes it harder to find the error when the build fails.
Avoid this issue by using a single step in the `script`.
=> Avoid running javadoc:jar if build fails

cloud-spanner-r2dbc-sample/pom.xml, cloud-spanner-r2dbc-sample/src/test/java/com/example/BookExampleAppIT.java, cloud-spanner-r2dbc/pom.xml, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerColumnMetadataTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfigurationTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryMetadataTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProviderTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionMetadataTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerResultTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerRowMetadataTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerRowTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerStatementTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/client/GrpcClientTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/codecs/DefaultCodecsNegativeTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/codecs/DefaultCodecsTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerDdlIT.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerIT.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerTestKit.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/result/PartialResultRowExtractorTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/statement/StatementBindingsTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/statement/StatementParserTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/util/AssertTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/util/CollectionsBuilderTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/util/ObservableReactiveUtilTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/util/SpannerExceptionUtilTest.java, pom.xml
So that was a 3 line change. But it turns out that running TestKit (which is a JUnit5 test suite) makes old JUnit4 tests not run. I could have added vintage engine to pom, but this seemed like a good point to migrate tests to JUnit5.
Most test changes are boilerplate except for Codec tests (parametrization and exception validation changed).
Fixes #176 .
=> Make TestKit run with other integration tests

README.md
Users don't need to manually run `SELECT 1` anymore.
=> Connection.validate() as a way to keep connection alive

README.md
Fixes the broken link referencing prefetch in r2dbc docs.
=> Fix the link mentioning prefetch in r2dbc docs.

pom.xml
* Upgrade libraries-bom to 4.0.0
* Removes `google-auth-library-oauth2-http`, as the BOM manages this version now.
Fixes #213 .
=> Upgrade cloud libraries BOM and remove auth library version override

cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/README.adoc, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/pom.xml, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/Book.java, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/BookRepository.java, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/RestController.java, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/SpringDataR2dbcApp.java, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/WebController.java, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/resources/static/index.html, cloud-spanner-r2dbc-samples/pom.xml
This sample creates a table called BOOK on application startup, and deletes it prior to application shutdown.
It provides three endpoints showing Spring Data R2DBC manipulation of Cloud Spanner data:
1) `/list` returns all books in the `BOOKS` table using the autoconfigured `DatabaseClient`.
2) `/add` inserts a book using the semantic insert in the autoconfigured `DatabaseClient`.
3) `/search/{id}` finds a specific book by ID using Spring Data R2DBC repository.
I owe an integration test, which I'd like to add in a follow-up PR.
=> Cloud Spanner - R2DBC - Spring data sample

cloud-spanner-spring-data-r2dbc/README.md
Add a refdoc for using Spring Data R2DBC with Cloud Spanner.
I included a basic summary, setup instructions, and sample application links. Kept the refdoc short; I found that additional details on how to use spring data r2dbc would duplicate the content in the standard [spring data r2dbc docs](https://github.com/spring-projects/spring-data-r2dbc#features).
=> Add refdoc for Spring Data R2DBC Dialect

cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/pom.xml
The Spring Boot BOM links to the old snapshot version (#221), but regardless the sample should depend on the latest snapshot from current project.
=> Fix driver version to current snapshot

cloud-spanner-r2dbc-samples/cloud-spanner-r2dbc-sample/pom.xml, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/pom.xml, cloud-spanner-r2dbc-samples/pom.xml
1) Disable maven deploy on the sample
2) change group to reflect reality, as when it tried to deploy it was to the spring repo...
3) move mvn:exec application entry point where it belongs -- in the old sample instead of top-level samples dir.
=> disable deploy on the new sample

pom.xml
Sets maven jar plugin property `addDefaultImplementationEntries`.
The result is addition of an extra three lines to the manifest:
```
Implementation-Title: Google Cloud Spanner R2DBC Driver
Implementation-Version: 0.2.0-SNAPSHOT
Implementation-Vendor: Google LLC
```
Fixes #216.
=> Add Implementation-Version to generated jars

cloud-spanner-r2dbc/pom.xml, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/statement/StatementParser.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/statement/StatementParserTest.java, pom.xml
Updates to the latest Cloud Spanner client library and uses its Connection API to check query type.
Also updates cloud libraries BOM, but it has not had time to pull in the newest Cloud Spanner client library, so an override is needed.
Co-authored-by: @dmitry-s
Fixes #236.
=> Switch StatementParser to pass through to the facade

cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatement.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnection.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryDmlStatement.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryStatement.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIntegrationTest.java
Fixes #253 
Fixes #242.
Fixes #254, since I refactored Select/DML statements to inherit from the same `AbstractSpannerClientLibraryStatement` (happy to rename it more meaningfully to `ParameterBindingClientLibraryStatement`).
Other changes:
* Renamed some `DatabaseClientReactiveAdapter` state fields for readability: currentTransactionFuture -> txnContext, asyncTransactionLastStep -> lastStep.
* I changed the future-to-publisher conversion helpers to return void and to send data to a passed-in publisher sink because helper methods returning `ApiFuture` proved impossible to adapt for SELECT statements: `.then()` expects an ApiFuture, but all SELECT functionality returns `AsyncResultSet`. So there was a conflict between the type that can be converted to a Flux (`AsyncResultSet`) and the type …
=> Run SELECT statements in transactions

cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProvider.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnection.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnectionFactory.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryDdlStatement.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIT.java
DDL execution now goes through the client library, which allowed `SpannerConnectionFactoryProvider` to finally remove the vestigial `GrpcClient` from V2.
Other changes:
* Folded `databaseClient`/`databaseAdminClient` into `DatabaseClientReactiveAdapter`, simplifying `SpannerClientLibraryConnection`, which no longer needs those or any configuration.
* Renamed `ClientLibraryBasedIntegrationTest` to `ClientLibraryBasedIT` for consistency, and to stop confusing failsafe, which we did not set up to pick up the former pattern.
* Renamed `DatabaseClientReactiveAdapter.runSelectStatement()` to `runSelectStatementAsFlux()` to avoid confusion between public and private overloaded methods. Also considered naming it `runSelectStatementInternal()` or `runSelectStatementWithCallback()`. Not sure …
=> Migrate V2 DDL execution to client library

.travis.yml
The presence of secure variables indicates that integration tests will run. `Install` phase skips tests, but `script` phase runs them, so the table re-creation is needed there.
=> Re-create tables if integration tests will run

cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatement.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryDmlStatement.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryStatement.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIT.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatementTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryDmlStatementTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryStatementTest.java
This PR covers the `Statement.bind().bind().add()` flow for both SELECT and DML.
Other changes:
* `AbstractSpannerClientLibraryStatement`
* Reduced visibility of most state to private.
* Implemented `execute` to complete the final row if necessary, and delegate actual query execution to abstract templated methods  `executeSingle()` and `executeMultiple()`.
* Added `runBatchDml()` method delegating to the client library's `TransactionContext.batchUpdateAsync()`.
* Refactored most of `runDmlStatement()` into a helper method, to be reusable by `runBatchDml().
* Re-enabled two TCK tests that needed the multi-bind functionality.
* Added many tests.
=> Bind multiple statements

cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfiguration.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnectionFactory.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnectionFactoryTest.java
`DatabaseClientReactiveAdapter` was already passing the configured project ID when creating `SpannerClient`. The project ID set in `SpannerOptions` is technically unused, but it seems worth explicitly setting it to the same value, so we don't have to wonder what value it is.
This PR also, since it's in the same configuration code:
* reintroduces User-Agent string for V2 (it was in a gRPC-specific implementation class in V1).
* propagates credentials. This required a small refactoring -- previously the code assumed GoogleCredentials, which precluded testing with NoCredentials.
Fixes #257.
=> Customize project ID, user-agent string from configuration

cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerTestKit.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerTestKitStatements.java, pom.xml
Remove TCK test overrides that were necessary due to DML syntax requiring column list in Spanner.
R2DBC SPI 0.8.3 containing the TCK changes was released. I also upgraded Reactor to the same version that's in SPI.
There are still two reasons for overrides:
1) Spanner returning `Long` even when `Integer` is requested -- work tracked in #276.
2) the driver breaking R2DBC spec by treating columns as case insensitive -- decision pending on #271.
=> Test new tck framework

pom.xml
Upgraded `libraries-bom` to the latest.
Spanner client library override is no longer needed, since the client library released async API, and the BOM had time to update.
=> Upgrade client library version

checkstyle/java.header, cloud-spanner-r2dbc/README_v2.adoc, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientTransactionManager.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnection.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnectionFactory.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/TransactionInProgressException.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIT.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientTransactionManagerTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnectionTest.java
Read/write and readonly transactions use completely different concepts in client library (`TransactionManager` is only for read/write transactions), so I created `DatabaseClientTransactionManager` to encapsulate all the random bits of transactional state.
All forms of stale readonly transactions are supported with this PR.
Partitioned DML is out of scope, since it does not fit into beginTransaction-runQueries-commitTransaction pattern, and it's not atomic anyway. It also does not happen to be supported asynchronously in the client library (although it is in Connection API, but more as a wrap-this-in-a-thread workaround). 
cc/ @olavloite
Fixes #249 .
=> V2 extended transactions

cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnection.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapterTest.java
Implements the `autoCommit` setting for the connection.
Fixes https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/issues/275
Reference: https://github.com/r2dbc/r2dbc-spi/blob/main/r2dbc-spec/src/main/asciidoc/transactions.adoc#auto-commit-mode
=> Add Autocommit Support

cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIT.java, pom.xml
Bring in the latest client library, with the fix for googleapis/java-spanner#514.
Fixes #282.
=> upgrade google BOM to pull in unpropagated failure fix

cloud-spanner-r2dbc/README_v2.adoc, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/CredentialsHelper.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfiguration.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProvider.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatement.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProviderTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIT.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatementTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapterTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryStatementTest.java
Getting this absolutely cursed (by Murphy's law, life, and random rabbitholes) PR out.
I still need to add `autocommit` and `readonly`.
Some properties are duplicated with the client library Connection API; those can be addressed incrementally. I'll also look to refactor a bit of Connection API's property initialization to avoid duplicate work of parsing with R2DBC SPI and then re-parsing in Connection API. But non of these is blocking for V2 release, seeing as Connection API is something of a nice-to-have.
Fixes #248.
=> Add config options to mirror JDBC driver

cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatement.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientTransactionManager.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnection.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryStatement.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProviderTest.java
This logging was useful during active development but does not serve an end-user purpose. Logging can be added back as needed.
This PR also injects mock credentials to keep unit test from interacting with environment
Fixes #261.
=> Remove unneeded logging

cloud-spanner-r2dbc/README_v2.adoc, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/BindingFailureException.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/ConversionFailureException.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/TransactionInProgressException.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/api/SpannerConnection.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryBinder.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryDecoder.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryTypeBinder.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryTypeBinderImpl.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientTransactionManager.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/LongIntegerConverter.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibrariesConverter.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryColumnMetadata.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnection.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConverters.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryDdlStatement.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryDmlStatement.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryResult.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryRow.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryRowMetadata.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryStatement.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIT.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryDecoderTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientTransactionManagerTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnectionFactoryTest.java
This PR restricts visibility of most v2 implementation classes because in the future, `.v2` package contents will move one level up, so nobody should be relying on the `.v2` classes directly. I moved type conversion classes up a level into `.v2` package to be able to reduce their visibility, too.
The only public class left is `SpannerClientLibraryConnectionFactory`, which needs to be visible to `SpannerConnectionFactoryProvider`. 
I moved all V2 exceptions up a level, since those have a legit reason to being referenced by end users.
Since we need to give users access to custom `SpannerClientLibraryConnection` methods for creating readonly transactions, `com.google.cloud.spanner.r2dbc.api.SpannerConnection` is a new interface allowing access to those methods without exposing …
=> Restrict visibility of public V2 implementation classes

cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryTypeBindersTest.java
Sonar got confused at whether `instrumentedBinder` ever got asserted. And I had to actually think about whether it did!
This was a cleverly done parameterized test, but the inlined basic tests are only a few more lines of code while being really easy to read.
I also added `unsupportedTypeThrowsException()`, which was a path not tested before.
=> Inline formerly parameterized test

cloud-spanner-r2dbc/pom.xml, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientTransactionManager.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapterTest.java, cloud-spanner-spring-data-r2dbc/pom.xml, cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/SpannerR2dbcDialect.java, cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/SpannerR2dbcDialectTest.java, pom.xml
* Extracting repeating string literals into constants
* Default must be at the end of the switch
* No generic wildcards in return (this required adding a `google-cloud-core` dependency at compile time to get access to `Timestamp` class; we've previously only had it for testing).
=> Sonar "critical" smells

cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerTestKit.java
Creating an independent constant in each TestKit class because the v1 TestKit will go away.
Sonar rule: "Either add an explanation about why this test is skipped or remove the "@Disabled" annotation."
=> Add reason to disabled tests

cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/codecs/Codec.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/codecs/Codecs.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/codecs/DefaultCodecs.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/codecs/SpannerCodec.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/statement/TypedNull.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/util/ObservableReactiveUtil.java
I am leaving some binder generic smells alone for now; it's going to be part of advanced parameter binding that's been merged in the SPI anyway.
=> Parameterize most generics

cloud-spanner-r2dbc-samples/cloud-spanner-r2dbc-sample/pom.xml, cloud-spanner-r2dbc-samples/cloud-spanner-r2dbc-sample/src/main/java/com/example/BookExampleApp.java, cloud-spanner-r2dbc-samples/cloud-spanner-r2dbc-sample/src/main/java/com/example/SampleApplication.java, cloud-spanner-r2dbc-samples/cloud-spanner-r2dbc-sample/src/test/java/com/example/BookExampleAppIT.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnection.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnectionFactory.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIT.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SessionCleanupUtils.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerDdlIT.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerIT.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerQueryUtil.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerTestKit.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnectionFactoryTest.java
Noticed during fixit that we were running out of available server side sessions. 
Spanner client library-based ConnectionFactory now implements R2DBC `Closeable`, as discussed in #284. Closing that out requires a small bit of documentation that I will do separately.
Fixes #310.
=> Cleanup tests properly to avoid session leaks

.github/workflows/sonar.yaml, .github/workflows/unitTests.yaml, README.md, RELEASING.adoc, cloud-spanner-r2dbc/pom.xml, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/util/SpannerExceptionUtil.java, cloud-spanner-spring-data-r2dbc/README.md
The link to Cloud Spanner client library changed just because it was for an outdated repo; no branch switch there yet.
=> Switch main branch to, well, main!

cloud-spanner-r2dbc/README_v2.adoc
This blurb went into a hard-to-discover README_v2.adoc. I will switch client library implementation to be primary, and restructure the docs next.
Fixes #284.
=> Document that user must close connection factory

cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/pom.xml, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/Book.java, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/SpringDataR2dbcApp.java, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/WebController.java, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/resources/application.properties, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnectionFactory.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnectionFactoryTest.java, cloud-spanner-spring-data-r2dbc/pom.xml, cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/SpannerBindMarkerFactoryProvider.java, cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/SpannerR2dbcDialect.java, cloud-spanner-spring-data-r2dbc/src/main/resources/META-INF/spring.factories, cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/SpannerBindMarkerFactoryProviderTest.java, cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/SpannerR2dbcDialectTest.java, cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/it/SpannerR2dbcDialectIntegrationTest.java, cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/it/entities/President.java, pom.xml
Spring Data dialect updates:
* Many supporting classes moved from Spring Data into Spring Framework.
* Spring Boot integration is no longer in experimental; it's part of mainstream Boot autoconfiguration.
* The need for `SpannerBindMarkerFactoryProvider` is a bit redundant since the same information can be derived from dialect, which is already getting autodiscovered. But it's documented [here](https://docs.spring.io/spring-framework/docs/current/reference/html/data-access.html#r2dbc-DatabaseClient).
Updated sample:
* Explicitly specifying `@Column` is needed because v1 is case-sensitive. We have fixed it to comply with case-insensitive spec for v2 in #271 , so this should become unnecessary when we migrate to v2.
Necessary but not sufficient step towards #314.
=> Upgrade to modern Spring Data R2DBC

cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/SpringDataR2dbcApp.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryDmlStatement.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryResult.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryStatement.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatementTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryDmlStatementTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryStatementTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerResultTest.java
V2 DML statement used to assume that `Result.getRowsUpdated()`  would always be called to trigger the reactive pipeline. However, the spec says either `getRowsUpdated()` or `map()` will be called, and Spring Data used the latter. This caused DML queries to never actually run when invoked through Spring Data.
There is a slight behavior change for SELECT statements -- they used to return an empty publisher as a result of `Result.getRowsUpdated()`, but now return a constant `0`. I think this is a change for the better, since semantically it's correct that 0 rows were updated for a SELECT.
Fixes #346.
=> Map DML result into R2DBC result to avoid disconnected publisher

README.md, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfiguration.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProvider.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/api/SpannerConnection.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnection.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnectionFactory.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProviderTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIntegrationTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnectionFactoryTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnectionTest.java
Minor but longstanding feature debt for parity with JDBC driver.
Also removes unused `SpannerConnectionConfiguration` parameter in connection.
Fixes #294, #295.
=> Change autocommit/readonly value on connection creation

cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProvider.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProviderTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerDmlReactiveStreamVerification.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerSelectReactiveStreamVerification.java
Long-standing request for consistency with JDBC driver and official product name.
We'll keep supporting the old name for a few versions.
The changes in reactive streams tests are an attempt to remove occasional flakes in CI.
=> Rename driver 

cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/pom.xml, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/SpringDataR2dbcApp.java, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/resources/application.properties, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/test/java/com/example/SpringDataR2dbcAppIntegrationTest.java
Also add integration test because we should have caught this at dependabot upgrade.
Fixes #404.
Fixes #218.
=> Move connection factory config to properties

cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerBatch.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnection.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryDmlStatement.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIntegrationTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatementTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapterTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerBatchTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryDmlStatementTest.java
This PR brings batch support to the same level that we had in v1 -- supporting batches of DML only.
R2DBC batches were meant for interspersed DML and SELECT. However, Cloud Spanner's `executeBatchDml` endpoint [only allows DML statements in the batch](https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1#google.spanner.v1.ExecuteBatchDmlRequest).
As part of implementation, the mapping from a `Mono<long[]>` to an R2DBC `Result` moved from the statement implementation to the `DatabaseClientReactiveAdapter`. It's an adapter from futures to R2DBC primitives... let it adapt fully instead of going halfway to an intermediate `Mono<long[]>`
Fixes #409
=> Implemented batching for DML

.github/workflows/integrationTests.yaml
Gcloud separated the auth step into a different action. Workload federation is recommended, but _(insert long story, available on demand)_ I am sticking with the path of least resistance and using the same JSON credential.
=> Use the new authentication way

cloud-spanner-r2dbc-samples/cloud-spanner-r2dbc-sample/pom.xml, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/pom.xml, cloud-spanner-r2dbc-samples/pom.xml, cloud-spanner-r2dbc/pom.xml, cloud-spanner-spring-data-r2dbc/pom.xml, pom.xml
We merge this once we confirm new release 1.1.0 is available in Maven Central https://repo1.maven.org/maven2/com/google/cloud/cloud-spanner-r2dbc/
=> Preparing next snapshot version 1.2.0-SNAPSHOT

README.md, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/Book.java, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/SpringDataR2dbcApp.java, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/WebController.java, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/resources/static/index.html, cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/test/java/com/example/SpringDataR2dbcAppIntegrationTest.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/SpannerType.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/ArrayToIterableBinder.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryBinder.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryDecoder.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryTypeBinder.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryTypeBinderImpl.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/IterableBinder.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SingleTypeBinder.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerTypeTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/Book.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIntegrationTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/TestDatabaseHelper.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/ArrayToIterableBinderTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryTypeBindersTest.java, cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/SpannerArrayColumns.java, cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/SpannerR2dbcDialect.java
This PR adds three additional types of parameter binding:
1) primitive arrays. These were straightforward to match, knowing the incoming object type, and are implemented with existing `ClientLibraryTypeBinderImpl`.
2) wrapper type arrays or primitive arrays where type conversion is needed. These need to be converted from an array to a list to use the list-accepting overloads of client library value binder. I've implemented a helper class `ArrayToIterableBinder` to avoid duplicating list creation boilerplate.
3) Iterable/Collection. This was harder, since the client library has typed binding methods, but parameterized types aren't real ("reified") in Java. This is, however, possible with R2DBC SPI 0.9 `Parameter.in()` binding. It's implemented with one binder for all `Iterable` needs -- …
=> Bind arrays and lists to Spanner native arrays

cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/pom.xml
Reverts #544, and set spring-boot-starter-parent to 2.6.8.
2.7.0 needs to be a manual update with #541, integration test fails with same error as #539
=> Bump spring-boot-starter-parent to 2.6.8 instead of 2.7.0

pom.xml
Reverts GoogleCloudPlatform/cloud-spanner-r2dbc#581.
This upgrade seems to have encountered a number of integration test failures, e.g.:
```
Error:  Tests run: 76, Failures: 15, Errors: 0, Skipped: 39, Time elapsed: 98.084 s <<< FAILURE! - in TestSuite
Error:  com.google.cloud.spanner.r2dbc.it.SpannerSelectReactiveStreamVerification.optional_spec104_mustSignalOnErrorWhenFails  Time elapsed: 0.217 s  <<< FAILURE!
java.lang.RuntimeException: Publisher threw exception (Error-state Publisher FluxFlatMap did not call `onError` on new Subscriber within 200 ms) instead of signalling error via onError!
at org.reactivestreams.tck.PublisherVerification.optional_spec104_mustSignalOnErrorWhenFails(PublisherVerification.java:384)
```
=> Revert "Bump libraries-bom from 26.1.1 to 26.1.2"

pom.xml
Upgrades libraries-bom back to 26.1.2 (revert of GoogleCloudPlatform/cloud-spanner-r2dbc#583), as the observed integration test failure was a flake unrelated to the dependabot upgrade, and has been successfully re-run.
=> Bump libraries-bom from 26.1.1 to 26.1.2

cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java
Attempting to re-enable these tests according to https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/issues/488
=> chore: re-enable SpannerClientLibraryTestKit tests

pom.xml
The shared release script uses `-DperformRelease` rather than setting a profile `-prelease` explicitly. The latter fails unless the profile is defined. This change activates the `release` profile (which correctly sets the modules and enables GPG signing) via the `performRelease` property.
=> build: activate the release profile with property

cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryStatement.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryStatementContextLossTest.java
fixes #685
Thanks @filipenfst for reporting the bug and proposing the fix. 
**Bug**: 
without the changes in [SpannerClientLibraryStatement](https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/pull/690/files#diff-8dc52019a2c3f21d622ff67a164701491c23275986a72dce82c805f32550edc9), the `SpannerClientLibraryStatementTest` would fail with context loss if context loss tracking is enabled. This [unit test](https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/blob/3e0c14ab8f9f8d6a4745198ac031e17648e03e62/cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryStatementContextLossTest.java) can be used to reproduce the error. 
```
Context loss after applying com.google.cloud.spanner.r2dbc.v2.SpannerClientLibraryStatement$$Lambda$451/0x0000000801285948@63 …
```
=> fix: Context loss after applying com.google.cloud.spanner.r2dbc.v2.SpannerClientLibraryStatement

.github/workflows/integrationTests.yaml, .github/workflows/unitTests.yaml
1. Github action shows warning:
``The `set-output` command is deprecated and will be disabled soon. ``
sample [log](https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/actions/runs/5157962559)
This change follows the upgrade guide and upgrades to using Environment Files
2. This pr also addresses `Node.js 12 actions are deprecated` warning on unit test and integration tests.
Github action announcement:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- For 'google-github-actions/auth@v1' and 'google-github-actions/setup-gcloud@v1', follow example [here](https://github.com/google-github-actions/setup-gcloud#service-account-key-json)
Note: turnstyle is not updated: …
=> chore: replace deprecated github action commands.

cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnection.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerConstants.java, cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerTransactionDefinition.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/util/TestTransactionDefinition.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnectionTest.java, cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerTransactionDefinitionTest.java
Implemented the following classes and methods to conform to R2DBC SPI which enables supporting `@Transactional` annotation in [Spring Data Dialect](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-spanner-spring-data-r2dbc).
- `Connection#beginTransaction(TransactionDefinition)` method so that it can be used by a `TransactionManager` when `@Transactional` annotation is used. ✅
- `Connection#getTransactionIsolationLevel` returns SERIALIZABLE as it is the closest level to EXTERNAL_CONSISTENCY which spanner supports. ✅
- `Connection#setTransactionIsolationLevel(IsolationLevel)` accepts only `IsolationLevel.SERIALIZABLE` and throw `UnsupportedOperationException` otherwise. ✅
- Introduced `SpannerTransactionDefinition`, an implementation of …
=> feat: Implementing Connection#beginTransaction(TransactionDefinition) to support @Transactional annotation

.github/workflows/sonar.yaml
Fixes https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/issues/770
Confirm "SonarCloud Analysis / Build with Sonar" passes before merging this. => It succeeded.
This change should update the author of the last edit.
=> ci: Java 17 for SonarCloud

.github/workflows/graalvmIntegrationTests.yaml
This is a LSC run by http://go/ghss to upgrade all depreacated ubuntu-20.04 runners to ubuntu-24.04.
On April 1, 2025, GitHub will stop supporting ubuntu-20.04 runners and workflows configured with this label will cease to run.  This PR is an attempt to save you work by doing the upgrade for you.
WARNING: We do not know if the updated label is compatiable with your workflow or not.
If you do not want to merge this PR, feel free to close it and deal with the problem yourselves.
More context and feedback: http://b/406537467
=> Update runners to ubuntu-24.04 from deprecated ubuntu-20.04 label
