- pom.xml
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerColumnMetadata.java
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfiguration.java
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryMetadata.java
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProvider.java
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerResult.java
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerRow.java
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerRowMetadata.java
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerColumnMetadataTest.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfigurationTest.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryMetadataTest.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryTest.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerResultTest.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerRowMetadataTest.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerRowTest.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerStatementTest.java
fixes #3 
placeholder SPI Classes
> placeholder SPI classes

- src/main/java/com/google/cloud/spanner/r2dbc/util/Assert.java
- src/test/java/com/google/cloud/spanner/r2dbc/util/AssertTest.java
> Return original value upon successfully asserting non-nullity

- src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfiguration.java
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactory.java
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProvider.java
- src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfigurationTest.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProviderTest.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryTest.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java
- src/test/resources/test_creds.json
Refactor GrpcClient to accept credentials through the constructor.
Fixes #31.
> Pass Credentials through GrpcClient

- src/test/java/com/google/cloud/spanner/r2dbc/result/PartialResultRowExtractorTest.java
fixes #70 
tests metadata colum names properly.
> Test metadata column name fix

- pom.xml
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerRowMetadata.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java
> Enhance test to verify that the innermost mono returned by client actually runs

- src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java
- src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerIT.java
This improves the detection of DML vs. Read queries by checking if the metadata's field list is empty or not; this appears to be the only reliable indicator to distinguish between the two types.
Fixes #77.
Fixes #75.
> Improve detection of DML vs Read queries

- src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java
- src/test/java/com/google/cloud/spanner/r2dbc/client/GrpcClientTest.java
fixes #69 
Added a user agent value with version and test.
> added user agent to channel

- src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerIT.java
Refactors Spanner integration tests to reduce code duplication.
> Refactor Spanner Integration Tests

- .travis.yml
- src/main/java/com/google/cloud/spanner/r2dbc/codecs/ArrayCodec.java
- src/main/java/com/google/cloud/spanner/r2dbc/codecs/Codec.java
- src/main/java/com/google/cloud/spanner/r2dbc/codecs/DefaultCodecs.java
- src/main/java/com/google/cloud/spanner/r2dbc/codecs/SpannerCodec.java
- src/main/java/com/google/cloud/spanner/r2dbc/statement/StatementBindings.java
- src/test/java/com/google/cloud/spanner/r2dbc/it/Book.java
- src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerIT.java
- src/test/java/com/google/cloud/spanner/r2dbc/statement/StatementBindingsTest.java
fixes #104  
fixes #14 
writes multi-MB rows and fixes an issue writing array-columns and tests
> Large test and fix

- pom.xml
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfiguration.java
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactory.java
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProvider.java
- src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java
- src/main/java/com/google/cloud/spanner/r2dbc/client/Client.java
- src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfigurationTest.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java
- src/test/java/com/google/cloud/spanner/r2dbc/SpannerStatementTest.java
- src/test/java/com/google/cloud/spanner/r2dbc/client/GrpcClientTest.java
- src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerDdlIT.java
- src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerIT.java
- src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerQueryUtil.java
Adds support for executing DDL statements from `SpannerStatement`.
> Add support for executing DDL statements

- pom.xml
- sample/README.adoc
- sample/src/main/java/com/example/BookExampleApp.java
- sample/src/main/java/com/example/SampleApplication.java
- sample/src/test/java/com/example/BookExampleAppTest.java
related #93 
sample with DML, DDL, SQL and readme
> DDL DML SQL sample and readme

- README.md
> Document supported types

- README.md
- src/main/java/com/google/cloud/spanner/r2dbc/codecs/DefaultCodecs.java
- src/main/java/com/google/cloud/spanner/r2dbc/codecs/SpannerCodec.java
- src/main/java/com/google/cloud/spanner/r2dbc/codecs/ValueUtils.java
- src/test/java/com/google/cloud/spanner/r2dbc/codecs/DefaultCodecsTest.java
> Use ByteBuffer for BYTE Spanner type

- README.md
fixes #115 
backpressure readme section
> back pressure readme

- README.md
Add setup instructions for the driver to the README.
> Add Setup Instructions for R2DBC Driver

- README.md
fixes #118 
param binding readme
> param binding readme

- README.md
> Fix Typo in Docs

- README.md
Adds sections about authentication and credentials to the docs.
Fixes #116.
> Add Doc Sections about Credentials and Authentication

- src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java
rename unit tests for connection
> rename unit tests for connection

- README.md
Add docs about statements.
Fixes #113.
> Add Documentation about Statements

- README.md
Add documentation about transaction types.
Fixes #117.
> Add docs about Transaction Types

- README.md
This adds docs about exception handling.
Fixes #114.
> Add documentation on exception handling

- README.md
Adds docs on dropped sessions.
Fixes #96.
> Add docs about dropped sessions/connections.

- README.md
Clarify concepts regarding backpressure and prefetch in the documentation.
Based on my research, the fetch-size setting is a bit more nuanced and could be additionally clarified.
Updated the docs with more information.
See:
https://stackoverflow.com/questions/56675511/what-does-prefetch-mean-in-project-reactor
https://projectreactor.io/docs/core/release/reference/#_on_backpressure_and_ways_to_reshape_requests
Fixes #152.
> Clarify backpressure concepts in the docs.

- README.md
- pom.xml
- src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerExample.java
> document r2dbc-pool usage

- README.md
- src/main/java/com/google/cloud/spanner/r2dbc/codecs/DefaultCodecs.java
- src/main/java/com/google/cloud/spanner/r2dbc/codecs/ValueUtils.java
- src/test/java/com/google/cloud/spanner/r2dbc/codecs/DefaultCodecsTest.java
> change timestamp type to LocalDateTime

- src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerTestKit.java
Speeds up TCK test setup.
Fixes #174 .
> Make table creation conditional on missing tables

- cloud-spanner-r2dbc-sample/pom.xml
- cloud-spanner-r2dbc/pom.xml
- pom.xml
0.1.0 released; long live 0.2.0-SNAPSHOT
> bump snapshot versions to 0.2.0

- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java
Consistent with spring-cloud/spring-cloud-gcp#2085.
> Update to gRPC target instead of address

- cloud-spanner-spring-data-r2dbc/pom.xml
- cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/SpannerR2dbcDialect.java
- cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/SpannerR2dbcDialectProvider.java
- cloud-spanner-spring-data-r2dbc/src/main/resources/META-INF/spring.factories
- cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/it/SpannerR2dbcDialectIT.java
- cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/it/SpannerTestUtils.java
- cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/it/entities/President.java
- pom.xml
This adds the Spring-Data R2DBC dialect to the repo and also adds an integration test.
> Add spring-data r2dbc dialect to repo

- cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/pom.xml
Spring Boot autoconfiguration for R2DBC is still at milestone level, even in experimental.
This should fix the build.
> Add milestones repo to the sample

- cloud-spanner-r2dbc/pom.xml
The link to the github repo in the pom file 404s currently.
> update github url

- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java
- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionMetadata.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionMetadataTest.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java
Please verify the PR raised for using SpannerConnectionMetadata in the connection.
Fixes #199.
> Implemented SpannerConnectionMetadata in the connection.

- pom.xml
Preparing for 0.2.0 release:
* bumped dependency versions.
* added dialect to the release profile so it actually gets released
* removed the non-profile modules section that keeps popping up.
> bump versions, add dialect to release profile

- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfiguration.java
- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProvider.java
- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnection.java
- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryDdlStatement.java
- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryStatement.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfigurationTest.java
> Customizable executor thread count 

- .travis.yml
- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryBinder.java
- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryDecoder.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIT.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryDecoderTest.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryTypeBindersTest.java
- pom.xml
> Numeric type support

- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatement.java
- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryBinder.java
- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java
- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnection.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryTypeBindersTest.java
Copied V1 TCK tests, fixed some of the obvious issues they found. Filed issues for the rest, so we can fix them as we go.
> Add v2 TCK tests

- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryColumnMetadata.java
- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryResult.java
- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryRow.java
- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryRowMetadata.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIT.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerResultTest.java
> V2  row metadata

- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java
- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnection.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIT.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java
This adds support for a Spanner connection health check.
Fixes #274 .
> Add support for a connection healthcheck

- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryRowMetadata.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryRowMetadataTest.java
> support case-insensitive column names

- README.md
- cloud-spanner-r2dbc-samples/cloud-spanner-r2dbc-sample/pom.xml
- cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/pom.xml
- cloud-spanner-r2dbc-samples/pom.xml
- cloud-spanner-r2dbc/pom.xml
- cloud-spanner-spring-data-r2dbc/pom.xml
- pom.xml
* 0.4.0-SNAPSHOT is the new development artifact.
* 0.3.0 is the latest released version.
> Bump snapshots to 0.4.0

- .github/workflows/sonar.yaml
- pom.xml
The GHA job will fail until we are granted access for this repo (email out asking for that).
> Configure code coverage & SonarCloud GitHub Action

- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientTransactionManager.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientTransactionManagerTest.java
> Fix NPE in commit

- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/codecs/DefaultCodecsTest.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryDecoderTest.java
Missed the parameterized ones.
> Remove remaining public modifiers from tests

- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfigurationTest.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionFactoryProviderTest.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/SpannerStatementTest.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/codecs/DefaultCodecsNegativeTest.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerDdlIT.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientTransactionManagerTest.java
Sonar rule: "Refactor the code of the lambda to have only one invocation possibly throwing a runtime exception."
> Only wrap a single statement in assertThrows

- .github/workflows/unitTests.yaml
Moving from Travis CI to GitHub Actions for consistency.
> Add config yaml file for GitHub Actions

- RELEASING.adoc
> Add post-release instruction to update BOM

- pom.xml
Migrates to new sonatype endpoint to fix continuous build.
> Updates sonatype endpoint

- RELEASING.adoc
- cloud-spanner-r2dbc-samples/cloud-spanner-r2dbc-sample/pom.xml
- cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/pom.xml
- cloud-spanner-r2dbc-samples/pom.xml
- cloud-spanner-r2dbc/pom.xml
- cloud-spanner-spring-data-r2dbc/pom.xml
- pom.xml
> Update current version to 1.0.0-SNAPSHOT

- cloud-spanner-r2dbc-samples/cloud-spanner-r2dbc-sample/README.adoc
- cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/README.adoc
> add open-in-cloudshell button to sample readmes.

- cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/pom.xml
- cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/Book.java
- cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/test/java/com/example/SpringDataR2dbcAppIntegrationTest.java
- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryRow.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIntegrationTest.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryDdlIntegrationTest.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/ReactiveResultSetCallbackTest.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryStatementTest.java
- cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerResultTest.java
- pom.xml
> fix: row column indexing in SpannerClientLibraryRow

- .github/workflows/unitTests.yaml
> fix: add java17 in unit tests

- .github/sync-repo-settings.yaml
> fix: add `sync-repo-settings.yaml`

- .github/workflows/integrationTests.yaml
- .github/workflows/unitTests.yaml
Fixes https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/issues/868
> fix: Deprecation notice: v3 of the artifact actions

- cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnection.java
> feat: implement getMetadata for SpannerClientLibraryConnection

- .github/workflows/sonar.yaml
Fixes https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/issues/873
> fix: upgrade action/cache
